### ISSUE TITLE
how can i layout message ？

### ISSUE THREAD

**Issue by whbq** [log4js-node/logFaces-HTTP#1]
how can i layout message ？

**Comment by whbq** [comment]
i want get more infomation,such as line,file .

**Comment by sparklton** [comment]
@whbq the line and file information will be available as soon as this pull request gets absorbed into the base:
https://github.com/log4js-node/logFaces-HTTP/pull/7

regarding laying out the message - once messages arrive to logFaces server, you will be able to layout and format them in many ways using logFaces client viewer.
